services:  
  postgres-db:
    hostname: gymcms-db
    ports:
      - "5442:5432"
    image: postgres:alpine
    environment:
      POSTGRES_DB: gym_cms_db
      POSTGRES_USER: damcio
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - database-gymcms:/data/postgres
    restart: always 


volumes:
  database-gymcms: