server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/gym_cms_db
    username: damcio
    password: password
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
     mode: always
  security:
    user:
      name: admin
      password: admin
  mail:
    host: smtp.gmail.com
    port: 587
    username: email.service1605@gmail.com
    password: pkkatnpnjczzbdws
    properties:
      sender:
        name: GymCms
      mail:
        smtp:
          auth: true
          starttls:
              enable: true
#    jwt:
#      secret-key: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
#      expiration-time: 3600000